// generated by Fast Light User Interface Designer (fluid) version 1.0303

#ifndef window_h
#define window_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Button.H>
#include <FL/Fl_Box.H>
#include <FL/Fl_Input.H>
#include <FL/Fl_Text_Display.H>
#include <FL/Fl_Browser.H>

class UserInterface {
public:
  UserInterface();
protected:
  Fl_Double_Window *w;
  Fl_Button *btSortear;
  Fl_Box *boxResult;
  Fl_Button *btReset;
public:
  Fl_Input *numGuests_in;
  Fl_Text_Display *xGanhador;
  Fl_Browser *line_browser;
};
#endif
